---
apiVersion: v1
kind: Service
metadata:
  name: jks21
  labels:
    app: jks21
spec:
  ports:
    - port: 5000
  selector:
    app: jks21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jks21
  labels:
    app: jks21
spec:
  selector:
    matchLabels:
      app: jks21
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jks21
    spec:
      containers:
      - image: voyager1122/jks21:latest
        name: jks21
        env:
        ports:
        - containerPort: 5000
          name: jks21
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jks21-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "jks21.k8s-53.sa"
spec:
  rules:
    - host: jks21.k8s-53.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jks21
                port:
                  number: 5000